### PR TITLE
Translate Navigation Group

### PR DESCRIPTION
**Pull request by mstfkhazaal**

### CODE REVIEW

**Comment by RickDBCN** [comment]
Thanks!

**Comment by mstfkhazaal** [comment]
Welcome

**Comment by RickDBCN** [comment]
Hi @mstfkhazaal, I unfortunately had to revert this PR. See issue #25 
Any chance you could fix?

**Comment by mstfkhazaal** [comment]
I will fix it

> Hi @mstfkhazaal, I unfortunately had to revert this PR. See issue #25 Any chance you could fix?

**Comment by mstfkhazaal** [comment]
> Hi @mstfkhazaal, I unfortunately had to revert this PR. See issue #25 Any chance you could fix?
You have created a draft pull request
I added try and catch
Can someone try test it to make sure there is no problem with it?

**Pull request merged**
