### PR TITLE
Update ViewEmail.php

### PR DESCRIPTION
**Pull request by marcogermani87**
Autoload custom Resource from config

### CODE REVIEW

**Comment by RickDBCN** [comment]
Thanks!

**Comment by marcogermani87** [comment]
> Thanks!

Hi Rick, i've made some interesting changes on my fork (https://github.com/marcogermani87/filament-email/):
- Loading plugin throgh ::make() method
- Table and form view rework
- Advanced search for created_at field (From/To date)
- Added translations support (EN/IT for now)
- Confirm modal for re-send e-mail action
- Scoped filter for Email model for enhance table free search

Take a look and if you agree i can make a PR for this changes.

Regards.

**Comment by RickDBCN** [comment]
> > Thanks!
> 
> Hi Rick, i've made some interesting changes on my fork (https://github.com/marcogermani87/filament-email/):
> 
>     * Loading plugin throgh ::make() method
> 
>     * Table and form view rework
> 
>     * Advanced search for created_at field (From/To date)
> 
>     * Added translations support (EN/IT for now)
> 
>     * Confirm modal for re-send e-mail action
> 
>     * Scoped filter for Email model for enhance table free search
> 
> 
> Take a look and if you agree i can make a PR for this changes.
> 
> Regards.

Hi Marco! Great work! :)
Could you make a PR for these changes? Would be highly appreciated.

Can you update the screenshots to English?

Many thanks!

**Comment by marcogermani87** [comment]
> > > Thanks!
> > 
> > 
> > Hi Rick, i've made some interesting changes on my fork (https://github.com/marcogermani87/filament-email/):
> > ```
> > * Loading plugin throgh ::make() method
> > 
> > * Table and form view rework
> > 
> > * Advanced search for created_at field (From/To date)
> > 
> > * Added translations support (EN/IT for now)
> > 
> > * Confirm modal for re-send e-mail action
> > 
> > * Scoped filter for Email model for enhance table free search
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Take a look and if you agree i can make a PR for this changes.
> > Regards.
> 
> Hi Marco! Great work! :) Could you make a PR for these changes? Would be highly appreciated.
> 
> Can you update the screenshots to English?
> 
> Many thanks!

Yes, sure! I'll try to do this tonight.

**Pull request merged**
